export { default as MultipleChoice } from './MultipleChoice'
export { default as TextInput } from './TextInput'
export { getTranslationText } from './translationHelper'
export type { MultipleChoiceProps } from './MultipleChoice'
export type { TextInputProps } from './TextInput'
