export const FRASES_DIA_A_DIA: Array<{ pt: string; ru: string }> = [
  { pt: 'Quanto custa?', ru: 'Сколько стоит?' },
  { pt: 'Quanto é?', ru: 'Сколько с меня?' },
  { pt: 'Queria...', ru: 'Я бы хотел(а)...' },
  { pt: 'Um quilo de...', ru: 'Один килограмм...' },
  { pt: 'Meio quilo de...', ru: 'Полкило...' },
  { pt: 'Pode pesar isto, por favor?', ru: 'Можете это взвесить, пожалуйста?' },
  { pt: 'Só duas ou três unidades.', ru: 'Только две или три штучки.' },
  { pt: 'Aceitam cartão?', ru: 'Принимаете карту?' },
  { pt: 'Onde é a caixa?', ru: 'Где касса?' },
  { pt: 'Preciso de um saco.', ru: 'Мне нужен пакет.' },
  { pt: 'Quanto custa isto tudo?', ru: 'Сколько стоит это всё?' },
  { pt: 'Quanto é tudo?', ru: 'Сколько за всё?' },
  { pt: 'Fica para a próxima vez', ru: 'Возможно в следующий раз' },
  { pt: 'Gostei imenso', ru: 'Мне очень понравилось' },
  { pt: 'Quentinho', ru: 'Горяченький' },
  { pt: 'Repôr energias', ru: 'Восстановить силы' },
  { pt: 'Quem fala?', ru: 'Кто говорит?' },
  { pt: 'Há tanto tempo', ru: 'Так долго / Столько времени' },
  { pt: 'Fica bem', ru: 'Будь здоров / Пока' },
  { pt: 'É o próprio', ru: 'Это он сам' },
  { pt: 'A rede', ru: 'Сеть' },
  { pt: 'O código', ru: 'Код' },
  { pt: 'Tudo ótimo', ru: 'Всё отлично' },
  { pt: 'Além disso', ru: 'Кроме того' },
  { pt: 'É verdade', ru: 'Это правда' },
  { pt: 'Algo', ru: 'Что-то' },
  { pt: 'Alguém', ru: 'Кто-то' },
  { pt: 'Nada', ru: 'Ничего' },
  { pt: 'Ninguém', ru: 'Никто' },
  { pt: 'Ah, como é?', ru: 'Что? / Как?' },
  { pt: 'Posso falar com a...?', ru: 'Могу поговорить с...?' },
  { pt: 'Cá fala...', ru: 'Это говорит...' },
  { pt: 'Não posso falar agora', ru: 'Я не могу сейчас говорить' },
  { pt: 'Volte a ligar mais tarde', ru: 'Перезвоните позже' },
  { pt: 'Estás a brincar', ru: 'Ты шутишь' },
  { pt: 'Só um momento', ru: 'Одну минуту' },
  { pt: 'Combinado', ru: 'Договорились' },
  { pt: 'Tanto faz', ru: 'Всё равно' },
  { pt: 'Vou chegar cinco minutos atrasado', ru: 'Я опоздаю на 5 минут' },
  { pt: 'Vamos ao restaurante chinês ou indiano?', ru: 'Пойдём в китайский или индийский ресторан?' },
  { pt: 'Encontramo-nos à porta do cinema', ru: 'Встретимся у входа в кино' },
  { pt: 'Vamos fazer o almoço', ru: 'Давай приготовим обед' },
  { pt: 'Diga, faz favor', ru: 'Говорите, пожалуйста' },
  { pt: 'É ida e volta', ru: 'Туда и обратно' },
  { pt: 'Aquele café é mais agradável, não achas?', ru: 'То кафе приятнее, не думаешь?' },
  { pt: 'Prefiro ir para lá', ru: 'Я предпочитаю пойти туда' },
  { pt: 'Temos pouco tempo', ru: 'У нас мало времени' },
  { pt: 'Boa sorte', ru: 'Удачи' },
  { pt: 'Boa viagem', ru: 'Хорошей поездки' },
  { pt: 'Não há problema', ru: 'Нет проблем' },
  { pt: 'Pronto', ru: 'Готово / Ладно' },
  { pt: 'Que tal?', ru: 'Как дела?' },
  { pt: 'Um beijo', ru: 'Поцелуй' },
  { pt: 'Saudades', ru: 'Скучаю / Тоска' },
  { pt: 'A sala de espera', ru: 'Зал ожидания' },
  { pt: 'Toda a gente', ru: 'Все' },
  { pt: 'Com atraso', ru: 'С опозданием' },
  { pt: 'Vire à direita e siga em frente', ru: 'Поверните направо и идите прямо' },
  { pt: 'Passe o cruzamento e vá em frente', ru: 'Проедьте перекрёсток и двигайтесь прямо' },
  { pt: 'Vá até ao fim da rua e depois vire à direita', ru: 'Идите до конца улицы и потом поверните направо' },
  { pt: 'Vá por aquela rua e vire na segunda à esquerda', ru: 'Идите по той улице и поверните на второй налево' },
  { pt: 'Contorne a rotunda e passe o semáforo', ru: 'Объедьте круг и проедьте светофор' },
  { pt: 'Apanhe a linha verde e saia na última estação', ru: 'Сядьте на зелёную линию и выйдите на последней станции' },
  { pt: 'Prova a sopa', ru: 'Попробуй суп' },
  { pt: 'Senta-te aqui', ru: 'Сядь здесь' },
  { pt: 'Ouve esta música', ru: 'Послушай эту музыку' },
  { pt: 'Vê este filme', ru: 'Посмотри этот фильм' },
  { pt: 'Divirta-se', ru: 'Развлекайтесь' },
  { pt: 'Põe isso aqui', ru: 'Положи это сюда' },
  { pt: 'Dorme bem', ru: 'Спи хорошо' },
  { pt: 'Espera por mim', ru: 'Подожди меня' },
  { pt: 'Desce por aqui', ru: 'Спустись здесь' },
  { pt: 'Serve o vinho', ru: 'Налей вино' },
  { pt: 'Para na esquina', ru: 'Остановись на углу' },
  { pt: 'Leva dinheiro', ru: 'Возьми деньги' },
  { pt: 'Descobre', ru: 'Узнай / Открой' },
  { pt: 'Para acabar', ru: 'В завершение' },
  { pt: 'E ponha ao lume durante...', ru: 'И поставьте на огонь на время...' },
  { pt: 'Eu não percebo nada', ru: 'Я ничего не понимаю' },
  { pt: 'O que devemos fazer?', ru: 'Что нам следует делать?' },
  { pt: 'Faz sempre o que quer', ru: 'Делает всегда, что хочет' },
]
